### ISSUE TITLE
Getting error in update cloud function, but create and delete function working fine.

### ISSUE THREAD

**Issue by itsmihir** [Kickbykick/Elastic-Cloud#2]
ResponseError: x_content_parse_exception     at onBody (/workspace/node_modules/@elastic/elasticsearch/lib/Transport.js:311:23)     at IncomingMessage.onEnd (/workspace/node_modules/@elastic/elasticsearch/lib/Transport.js:240:11)     at IncomingMessage.emit (events.js:327:22)     at IncomingMessage.EventEmitter.emit (domain.js:506:15)     at endReadableNT (_stream_readable.js:1220:12)     at processTicksAndRejections (internal/process/task_queues.js:84:21) | updatePost
-- | --

**Comment by itsmihir** [comment]
fixed with this
[https://stackoverflow.com/questions/57945828/elastic-js-node-js-unable-to-update-index](https://stackoverflow.com/questions/57945828/elastic-js-node-js-unable-to-update-index)
